### PR TITLE
Change font to Craft Mono

### PR DESCRIPTION
**Pull request by g33king**

### CODE REVIEW

**Comment by 3174N** [comment]
Thank you for contributing!
We recently switched from `css` to `less`, so please change your code to that format.

**Review by 3174N — CHANGES_REQUESTED** [review]
Thank you for contributing!
We recently switched from `css` to `less`, so please change your code to that format.

**Review by 3174N — CHANGES_REQUESTED** [review]
Another thing: we want the craft-mono font to be only on the file-view, and not on all of the UI.

**Comment by SFR-git** [comment]
The easy way to do so would be leaving the default font as-is, and adding a few lines for `craft-mono` as the fileview font.

**Review by 3174N — APPROVED** [review]
LGTM.

**Pull request merged**
